[package]
name = "ugt-graph"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nalgebra = { workspace = true }
ndarray = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
